### ISSUE TITLE
각 파일의 api를 정리해야된다고 생각합니다!

### ISSUE THREAD

**Issue by gkrry2723** [oss-nocheat/nocheat-server#9]
우리가 이 프로젝트를 완성시키려면 많은 다른 개발자들의 참여가 필요하므로 다른 개발자들이 보고 바로 개발에 참여할 수 있도록 api를 정리해서 문서를 올려야될 것 같습니다!

**Comment by gkrry2723** [comment]
makeSound는 api 추가함

**Comment by Choi-Ju12g** [comment]
generate_sound
find_mic_check
record api 추가 완료
